# Site Info
title: Zune2
tagline: 'Zune2 - Personal web site'
#description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
description: 'My Book Reading and Life story'
baseurl: "/blog"
url: http://codinfox.github.io
#logo: '/public/logo.png'

# Site configurations
plugins:
  - jekyll-toc
  - jekyll-paginate

markdown: kramdown


kramdown:
input: GFM
highlighter: rouge

excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 8
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Zune2
  description: Programmer, SW engineer
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
      #    linkedin:  https://www.linkedin.com/in/lizhihao
           github:    https://github.com/zune2
    # facebook:  <hide>
    #    twitter:   https://twitter.com/Li_Zhihao
    #    weibo:     http://weibo.com/41173780
    #    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
#  Github Project: 
#    - 'http://zune2.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/mypic.jpeg
  caption: It's me. Maybe.

# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
#disqus_short_name: 'ame' # leave blank if you don't want disqus
disqus_short_name: zune2
disqus_url: "http://zune2.github.io"
