# Site settings
title: Zune2
email: closure
description: > # this means to ignore newlines until "baseurl:"
  github에서 노는 것도 잼있군요.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  zune2
# Build settings
#markdown: kramdown
markdown: redcarpet
paginate: 5
paginate_path: "/archives/page:num"
redcarpet:
  extensions: ["strikethrough"]
