# Site settings
title: Zune2
email: myoungjune@gmail.com
description: My Book Reading
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: zune2 
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/zune2/zune2.github.com/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/zune2/zune2.github.com/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: zune2
disqus_url: "http://zune2.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
highlighter: rouge
# highlighter: false
plugins:
  - jekyll-toc

# The font used for headings. Expects a string that is a valid CSS font-family value.
font_heading:        "'Nanum Gothic', Helvetica, Arial, sans-serif"

# The text font. Expects a string that is a valid CSS font-family value.
font:                "'Noto Sans', 'Nanum Gothic', Helvetica, Arial, sans-serif"


