#+HTML: ---
#+HTML: title: abc200 D - Happy Birthday! 2
#+HTML: tags: AtCoder
#+HTML: ---
#+OPTIONS: ^:nil

** D - Happy Birthday! 2
- N이 최대 200까지
- B배열과 C배열을 A배열에서 분리해낸다.
  - 배열의 크기가 다르거나, 값이 달라야 한다.
- 비둘기집 원리를 문제에 적용해야 함. 생각이 쉽지 않다.

** TODO 접근하기
  - N <= 8까지 해도, 2^8-1 =255 경우를 찾을 수 있다.
  - 그 사이 답을 1개만 찾아서 출력하면 된다.
- bit연산 or재귀로 2^N 완전탐색 구현
- 1인 목록의 sum을 구하고 200으로 나머지셈 위치에 저장 (Hash table)
- 이후에 sum을 구해서 %200한 hash의 위치에 값이 있으면 출력하고, 자신도 출력

** 코드 - 완전탐색 이용
#+BEGIN_SRC cpp
#include <iostream>
#include <cstdio>
#include <vector>
#include <algorithm>
using namespace std;

int N;
int n;
int a[210];
int b[12];
int bend;

vector < vector<int> > v(200, vector<int>(0));

void bt(int idx)
{
    if (bend) return;

    if (idx >= n) {
        int sum = 0;
        vector <int> tmp;
        for(int i=0;i<n;i++) {
            if(b[i]) {
                sum += a[i];
                sum = sum % 200;
                tmp.push_back(i+1);
            }
        } 
        
        if (v[sum].size() == 0) {
            v[sum] = tmp;
        } else {
            printf("Yes\n");
            cout << tmp.size();
            for(auto &x : tmp) {
                cout << " " << x;
            }
            cout << endl;

            cout << v[sum].size();
            for(auto &x : v[sum]) {
                cout << " " << x;
            }
            cout << endl;
            bend = 1;
        }
        return;
    }

    b[idx] = 0;
    bt(idx+1);
    
    b[idx] = 1;
    bt(idx+1);
}

int main(int argc, char* argv[])
{
    scanf("%d", &N);
    
    for(int i=0;i<N;i++) {
        scanf("%d", &a[i]);
    }
    
    n = min(8, N); 
    bt(0);
    if (bend == 0)
        printf("No\n");
    return 0;
}
#+END_SRC

** 코드 - 비트연산 이용
#+BEGIN_SRC cpp
#include <iostream>
#include <cstdio>
#include <vector>
#include <algorithm>
using namespace std;

int N;
int n;
int a[210];

vector < vector<int> > v(200, vector<int>(0));

int main(int argc, char* argv[])
{
    scanf("%d", &N);
    
    for(int i=0;i<N;i++) {
        scanf("%d", &a[i]);
    }
    
    n = min(8, N); 

    for(int i=1;i<(1<<n);i++) {

        int sum = 0;
        vector <int> tmp;
        for(int j=0;j<n;j++) {
            if (i & (1<<j)) {
                sum += a[j];
                sum = sum % 200;
                tmp.push_back(j+1);
            }    
        }

        if (v[sum].size() == 0) {
            v[sum] = tmp;
        } else {
            printf("Yes\n");
            cout << tmp.size();
            for(auto &x : tmp) {
                cout << " " << x;
            }
            cout << endl;

            cout << v[sum].size();
            for(auto &x : v[sum]) {
                cout << " " << x;
            }
            cout << endl;
            return 0; 
        }
    }
    printf("No\n");
    return 0;
}
#+END_SRC
** 문제 링크
- https://atcoder.jp/contests/abc200/tasks/abc200_d

