#+HTML: ---
#+HTML: title: 팝송 몇 곡 정리
#+HTML: tag: Pops
#+HTML: ---
#+OPTIONS: ^:nil

** 보헤미안 랩소디

Is this the real life? Is this just fantasy?

Caught in a landslide, no escape from reality

Open your eyes, look up to the skies and see


I'm just a poor boy, I need no sympathy

Because I'm easy come, easy go

Little high, little low

Any way the wind blows doesn't really matter to me, to me


Mama, just killed a man

Put a gun against his head

Pulled my trigger, now he's dead

Mama, life had just begun

But now I've gone and thrown it all away


Mama, ooh

Didn't mean to make you cry

If I'm not back again this time tomorrow

Carry on, carry on

As if nothing really matters


Too late, my time has come

Sends shivers down my spine, body's aching all the time

Goodbye, everybody, I've got to go

Gotta leave you all behind and face the truth


Mama, oooh (Anyway the wind blows)

I don't wanna die

I sometimes wish I'd never been born at all



I see a little silhouetto of a man

Scaramouch[9], Scaramouch,

Will you do the fandango[10]?

Thunderbolts and lightning very very frightening me

Galileo, Galileo, Galileo, Galileo,

Galileo, Figaro, Magnifico oh oh oh

But I'm just a poor boy, nobody loves me

He's just a poor boy from a poor family

Spare him his life from this monstrosity

Easy come, easy go, will you let me go?

Bismillah![14][15] No, we will not let you go (Let him go)

Bismillah! We will not let you go (Let him go)

Bismillah! We will not let you go (Let me go)

Will not let you go - Let me go (Never)

Will not let you go - Let me go (Never, Never, Never)

Oh oh oh

No, no, no, no, no, no, no

Oh, mamma mia, mamma mia,

Mamma mia, let me go

Beelzebub has the devil put aside for me

for me, for me[17]



So you think you can stone me and spit in my eye?

So you think you can love me and leave me to die?[18]

Oh baby, can't do this to me, baby

Just gotta get out, just gotta get right outta here



Ooh, ooh yeah, ooh yeah, ooh
Nothing really matters

Anyone can see

Nothing really matters

Nothing really matters to me

Any way the wind blows




